#!/usr/bin/env python3
"""Record real phone apps (WhatsApp, etc.) through a real IKEv2 VPN as labelled sessions.

A strongSwan road-warrior server accepts a phone's built-in IKEv2/IPsec PSK client, all phone
traffic goes through the tunnel, and tcpdump on the server records the encrypted IKE/ESP.
Every recording is saved as <app>_<activity>_<nn>.pcap plus a .json label that also holds the
IKE/ESP settings the phone really negotiated (from strongSwan's own SA list).

Two ways to run the server:

  Docker (a Linux host with Docker):
    python3 testbed/scripts/record_real_app.py serve [--lan-ip 192.168.1.5] [--build]

  Local, directly on a Linux machine or VM (required on Windows laptops: Windows' TCP/IP stack
  swallows UDP-encapsulated ESP on port 4500, so use a VirtualBox VM with a bridged adapter):
    sudo python3 record_real_app.py --local serve --install [--psk KEY]

Then, in either mode:
    ... status
    ... record --app whatsapp --activity voice-call --seconds 120
    ... stop

See docs/whatsapp-live.md for the full procedure. Uses only the Python standard library.
"""
from __future__ import annotations

import argparse
import ipaddress
import json
import os
import platform
import re
import secrets
import shutil
import signal
import socket
import struct
import subprocess
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

TESTBED = Path(__file__).resolve().parents[1]
ROOT = TESTBED.parent
COMPOSE_FILE = TESTBED / "docker-compose.phone.yml"
CONFIG_DIR = TESTBED / "generated" / "phone"
PSK_FILE = TESTBED / "generated" / "phone-psk.txt"
SESSIONS = ROOT / "data" / "raw" / "traffic_sessions"
SERVICE = "vpn"
POOL = "10.10.10.0/24"
# Only the IPsec traffic between phone and server; the decrypted, forwarded app traffic is excluded.
CAPTURE_FILTER = "udp port 500 or udp port 4500"
ORIGIN = "real_app_phone_ikev2"
# What the person does on the phone -> traffic class (video calls follow the ISCX convention: Video).
ACTIVITIES = {
    "chat": "Chat", "voice-call": "VoIP", "video-call": "Video", "file": "File-Transfer",
    "status": "Video", "browse": "Web", "email": "Email",
}
PSK_ALPHABET = "abcdefghjkmnpqrstuvwxyz23456789"  # no 0/o, 1/l/i: easy to type on a phone
# Upper bound of the capture rate (KB/s, IPsec overhead included) an activity alone produces. Above it, other
# apps on the phone (updates, backups, sync) were almost certainly sharing the tunnel during the recording.
MAX_RATE_KBPS = {"chat": 8, "voice-call": 15}
BURSTY_ACTIVITIES = {"file", "status", "browse"}

# Local mode (Linux, run as root)
LOCAL_CONF = Path("/etc/swanctl/conf.d/phones.conf")
LOCAL_STATE = Path("/etc/swanctl/sih-phone.json")  # server address, interface and PSK between commands
LOCAL_SESSIONS = Path("/srv/sih-sessions")
LOCAL_DROPIN = Path("/etc/systemd/system/strongswan.service.d/sih-phone-nat.conf")
LOCAL_PACKAGES = ["charon-systemd", "strongswan-swanctl", "libcharon-extra-plugins", "libstrongswan-extra-plugins",
                  "libstrongswan-standard-plugins", "tcpdump", "iptables"]
VIRTUALBOX_NAT = ipaddress.ip_network("10.0.2.0/24")


# --- helpers shared by both modes ---------------------------------------------------------------

def lan_ip() -> str | None:
    """Address of the interface that holds the default route (a UDP connect sends nothing)."""
    with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as probe:
        try:
            probe.connect(("8.8.8.8", 80))
            return probe.getsockname()[0]
        except OSError:
            return None


def new_psk() -> str:
    return "".join(secrets.choice(PSK_ALPHABET) for _ in range(16))


def render(server_ip: str, psk: str) -> str:
    """swanctl config for phone clients: IKEv2, PSK, a virtual-IP pool and DNS, all traffic tunnelled."""
    return f"""# Generated by record_real_app.py. Do not edit.
connections {{
    phones {{
        version = 2
        pools = phones
        send_certreq = no
        unique = replace
        dpd_delay = 30s
        proposals = default, aes256-aes128-sha256-sha1-modp2048-modp1024
        local {{
            auth = psk
            id = {server_ip}
        }}
        remote {{
            auth = psk
            id = %any
        }}
        children {{
            internet {{
                local_ts = 0.0.0.0/0
                esp_proposals = default, aes256-aes128-sha256-sha1, aes256gcm16-aes128gcm16-ecp256-modp2048, aes256-aes128-sha256-sha1-modp2048-modp1024
                dpd_action = clear
            }}
        }}
    }}
}}
pools {{
    phones {{
        addrs = {POOL}
        dns = 8.8.8.8, 1.1.1.1
    }}
}}
secrets {{
    ike-phones {{
        secret = "{psk}"
    }}
}}
"""


def parse_sas(text: str) -> dict:
    """Connected phone and negotiated settings from `swanctl --list-sas` output."""
    info: dict = {"established": "ESTABLISHED" in text, "installed": "INSTALLED" in text}
    for line in text.splitlines():
        stripped = line.strip()
        if "ike_proposal" not in info and re.fullmatch(r"[A-Z0-9_]+(-\d+)?(/[A-Z0-9_]+(-\d+)?)+", stripped):
            info["ike_proposal"] = stripped
        if match := re.search(r"INSTALLED, (TUNNEL|TRANSPORT)(-in-UDP)?, ESP:(\S+)", stripped):
            info["mode"] = match[1].capitalize()
            info["nat_traversal"] = bool(match[2])
            info["esp"] = match[3].rstrip(",")
        if match := re.match(r"remote '([^']*)' @ ([^\[\s]+).*\[(\d+\.\d+\.\d+\.\d+)\]\s*$", stripped):
            info["phone_id"], info["phone_virtual_ip"] = match[1], match[3]
        if match := re.match(r"in\s+\S+,\s+(\d+) bytes,\s+(\d+) packets", stripped):
            info["bytes_in"], info["packets_in"] = int(match[1]), int(match[2])
    return info


def to_proposal(esp: str | None) -> str | None:
    """strongSwan SA notation (AES_GCM_16-256/ECP_256) -> proposal keywords (aes256gcm16-ecp256)."""
    parts = []
    for token in (esp or "").upper().split("/"):
        if match := re.fullmatch(r"AES_GCM_(\d+)-(\d+)", token):
            parts.append(f"aes{match[2]}gcm{match[1]}")
        elif match := re.fullmatch(r"AES_CBC-(\d+)", token):
            parts.append(f"aes{match[1]}")
        elif token.startswith("CHACHA20_POLY1305"):
            parts.append("chacha20poly1305")
        elif token.startswith("3DES"):
            parts.append("3des")
        elif token == "NULL":
            parts.append("null")
        elif match := re.fullmatch(r"HMAC_SHA2_(\d+)(_\d+)?", token):
            parts.append(f"sha{match[1]}")
        elif token.startswith("HMAC_SHA1"):
            parts.append("sha1")
        elif match := re.fullmatch(r"(MODP|ECP)_(\d+)", token):
            parts.append(f"{match[1].lower()}{match[2]}")
        elif token.startswith("CURVE_25519"):
            parts.append("curve25519")
    return "-".join(parts) or None


def rate_profile(pcap: Path, bucket: float = 10.0) -> dict:
    """Median and burst rates of a classic pcap in `bucket`-second slices (KB/s, whole frames).

    The median shows what the activity itself used; slices far above it are other apps' bursts."""
    data = pcap.read_bytes()
    if len(data) < 24:
        return {"median_kbps": 0.0, "bursts": []}
    endian = "<" if data[:4] in (b"\xd4\xc3\xb2\xa1", b"\x4d\x3c\xb2\xa1") else ">"
    slices: dict[int, int] = {}
    offset, start = 24, None
    while offset + 16 <= len(data):
        seconds, _, captured, original = struct.unpack(endian + "IIII", data[offset:offset + 16])
        start = seconds if start is None else start
        slices[int((seconds - start) // bucket)] = slices.get(int((seconds - start) // bucket), 0) + original
        offset += 16 + captured
    rates = [slices.get(i, 0) / bucket / 1000 for i in range(max(slices) + 1)] if slices else []
    median = sorted(rates)[len(rates) // 2] if rates else 0.0
    bursts = [(int(i * bucket), round(rate, 1)) for i, rate in enumerate(rates) if rate > max(3 * median, median + 30)]
    return {"median_kbps": round(median, 1), "bursts": bursts}


def next_name(app: str, activity: str, directory: Path = SESSIONS) -> str:
    taken = {p.stem for p in directory.glob(f"{app}_{activity}_*.json")}
    index = 0
    while f"{app}_{activity}_{index:02d}" in taken:
        index += 1
    return f"{app}_{activity}_{index:02d}"


def build_label(name: str, app: str, activity: str, traffic: str, seconds: float, sas: dict, raw_sas: str) -> dict:
    return {
        "session_id": name,
        "pcap_filename": f"{name}.pcap",
        "traffic": traffic,
        "group": name,  # each recording is its own group, so cross-validation never splits one recording
        "scenario": "phone-ikev2-roadwarrior",
        "app": app,
        "activity": activity,
        "ike_version": "IKEv2",
        "mode": sas.get("mode", "Tunnel"),
        "ip_version": "IPv4",
        "nat_traversal": sas.get("nat_traversal", True),
        "esp_proposal": to_proposal(sas.get("esp")),
        "negotiated": {"ike": sas.get("ike_proposal"), "esp": sas.get("esp")},
        "seconds": round(seconds, 1),
        "recorded_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "dataset_origin": ORIGIN,
        "note": "Real app on a phone's built-in IKEv2 client through the strongSwan road-warrior server; "
                "recorded on the server (UDP 500/4500 only, so the decrypted app traffic is not stored).",
        "negotiated_sas": raw_sas,
    }


def phone_instructions(server_ip: str, psk: str) -> str:
    return f"""
VPN server is running on {server_ip} (UDP 500 and 4500).

Add this VPN on the phone (the phone must be on the same Wi-Fi, and must NOT be the hotspot):
  Android (11+): Settings > Network & internet > VPN > +
      Name: SIH lab   Type: IKEv2/IPSec PSK   Server address: {server_ip}
      IPSec identifier: phone   IPSec pre-shared key: {psk}
  iPhone: Settings > General > VPN & Device Management > VPN > Add VPN Configuration
      Type: IKEv2   Description: SIH lab   Server: {server_ip}   Remote ID: {server_ip}
      Local ID: phone   User Authentication: None   Use Certificate: off   Secret: {psk}

Connect, open any website on the phone to check the internet works, then run `status`.
"""


# --- where the server runs -------------------------------------------------------------------------

class DockerServer:
    """strongSwan in the ipsec-phone compose project (Linux hosts)."""

    def __init__(self, out: Path | None) -> None:
        self.sessions = out or SESSIONS

    def compose(self, *args: str, check: bool = True, capture: bool = False) -> subprocess.CompletedProcess:
        command = ["docker", "compose", "-f", str(COMPOSE_FILE), *args]
        result = subprocess.run(command, text=True, capture_output=capture, check=False)
        if check and result.returncode != 0:
            detail = (result.stderr or result.stdout or "").strip() if capture else ""
            raise RuntimeError(f"Command failed ({result.returncode}): {' '.join(command)}\n{detail}")
        return result

    def run(self, *command: str, check: bool = True) -> subprocess.CompletedProcess:
        return self.compose("exec", "-T", SERVICE, *command, check=check, capture=True)

    def serve(self, args: argparse.Namespace) -> int:
        if platform.system() == "Windows":
            print("Note: on Windows the phone can connect but its data never reaches the server, because Windows' "
                  "TCP/IP stack consumes UDP-encapsulated ESP on port 4500. Use a Linux VM with a bridged adapter "
                  "and `--local` mode instead (docs/whatsapp-live.md).", file=sys.stderr)
            if not args.force:
                return 1
        server_ip = args.lan_ip or lan_ip()
        if not server_ip:
            print("Could not find this machine's network address; pass --lan-ip.", file=sys.stderr)
            return 1
        psk = args.psk or (PSK_FILE.read_text(encoding="utf-8").strip() if PSK_FILE.exists() else "") or new_psk()
        PSK_FILE.parent.mkdir(parents=True, exist_ok=True)
        PSK_FILE.write_text(psk + "\n", encoding="utf-8")
        CONFIG_DIR.mkdir(parents=True, exist_ok=True)
        (CONFIG_DIR / "phones.conf").write_text(render(server_ip, psk), encoding="utf-8", newline="\n")
        print("Starting the VPN server" + (" (building the image first; needs internet)" if args.build else "") + "...")
        self.compose("up", "-d", *(["--build"] if args.build else []))
        if not wait_for_charon(self):
            logs = self.compose("logs", "--tail", "20", SERVICE, check=False, capture=True).stdout
            print(f"The VPN server did not start. Last log lines:\n{logs}", file=sys.stderr)
            return 1
        return load_config(self, server_ip, psk)

    def start_capture(self, name: str):
        self.compose("exec", "-d", SERVICE, "tcpdump", "-i", "eth0", "-U", "-n", "-w", f"/sessions/{name}.pcap", CAPTURE_FILTER)
        return None

    def stop_capture(self, handle) -> None:
        self.run("pkill", "-INT", "tcpdump", check=False)
        for _ in range(20):
            if self.run("pgrep", "tcpdump", check=False).returncode != 0:
                return
            time.sleep(0.5)

    def stop(self) -> None:
        self.compose("down")


class LocalServer:
    """strongSwan installed directly on this Linux machine (e.g. a VirtualBox VM with a bridged adapter)."""

    def __init__(self, out: Path | None) -> None:
        self.sessions = out or LOCAL_SESSIONS

    def run(self, *command: str, check: bool = True) -> subprocess.CompletedProcess:
        result = subprocess.run(list(command), text=True, capture_output=True, check=False)
        if check and result.returncode != 0:
            raise RuntimeError(f"Command failed ({result.returncode}): {' '.join(command)}\n{(result.stderr or result.stdout).strip()}")
        return result

    @staticmethod
    def candidate_addresses() -> list[tuple[str, str]]:
        """(interface, IPv4) pairs other than loopback, VirtualBox NAT and container bridges."""
        output = subprocess.run(["ip", "-4", "-o", "addr", "show", "scope", "global"], text=True, capture_output=True).stdout
        pairs = []
        for line in output.splitlines():
            fields = line.split()
            interface, address = fields[1], fields[3].split("/")[0]
            if interface.startswith(("docker", "br-", "veth")) or ipaddress.ip_address(address) in VIRTUALBOX_NAT:
                continue
            pairs.append((interface, address))
        return pairs

    def serve(self, args: argparse.Namespace) -> int:
        if os.geteuid() != 0:
            print("Local mode configures strongSwan and iptables; run it with sudo.", file=sys.stderr)
            return 1
        if args.install or not shutil.which("swanctl"):
            print("Installing strongSwan, tcpdump and iptables (needs internet)...")
            subprocess.run(["apt-get", "update", "-q"], check=True)
            subprocess.run(["apt-get", "install", "-y", "-q", *LOCAL_PACKAGES], check=True,
                           env={**os.environ, "DEBIAN_FRONTEND": "noninteractive"})
        pairs = self.candidate_addresses()
        if args.lan_ip:
            chosen = next(((i, a) for i, a in pairs if a == args.lan_ip), None) or (args.interface or "", args.lan_ip)
        elif len(pairs) == 1:
            chosen = pairs[0]
        else:
            listing = ", ".join(f"{a} ({i})" for i, a in pairs) or "none"
            print(f"Found these addresses: {listing}. Pass the bridged one with --lan-ip "
                  "(it is on the same network as the phone).", file=sys.stderr)
            return 1
        interface, server_ip = args.interface or chosen[0], chosen[1]
        state = json.loads(LOCAL_STATE.read_text()) if LOCAL_STATE.exists() else {}
        psk = args.psk or state.get("psk") or new_psk()
        LOCAL_STATE.write_text(json.dumps({"server_ip": server_ip, "interface": interface, "psk": psk}))
        LOCAL_STATE.chmod(0o600)
        LOCAL_CONF.write_text(render(server_ip, psk))
        LOCAL_CONF.chmod(0o600)

        # Forward the phone's traffic to the internet (NAT) and clamp TCP MSS inside the UDP-encapsulated tunnel.
        # strongSwan starts on boot by itself, but forwarding and iptables rules do not survive a reboot, so they
        # are also installed as a systemd drop-in that runs before strongSwan starts. Without it the phone
        # connects after a VM restart but has no internet.
        rules = [("nat", f"POSTROUTING -s {POOL} ! -d {POOL} -j MASQUERADE"),
                 ("mangle", f"FORWARD -s {POOL} -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --set-mss 1300")]
        self.run("sysctl", "-w", "net.ipv4.ip_forward=1")
        for table, rule in rules:
            if self.run("iptables", "-t", table, "-C", *rule.split(), check=False).returncode != 0:
                self.run("iptables", "-t", table, "-A", *rule.split())
        LOCAL_DROPIN.parent.mkdir(parents=True, exist_ok=True)
        LOCAL_DROPIN.write_text("[Service]\nExecStartPre=/sbin/sysctl -w net.ipv4.ip_forward=1\n" + "".join(
            f"ExecStartPre=/bin/sh -c 'iptables -t {table} -C {rule} 2>/dev/null || iptables -t {table} -A {rule}'\n"
            for table, rule in rules))
        self.run("systemctl", "daemon-reload")
        self.run("systemctl", "enable", "strongswan", check=False)
        # charon-systemd's unit is "strongswan" on current Ubuntu/Debian, "strongswan-swanctl" on older releases.
        if self.run("systemctl", "restart", "strongswan", check=False).returncode != 0:
            self.run("systemctl", "restart", "strongswan-swanctl")
        if not wait_for_charon(self):
            print("strongSwan did not start; check `journalctl -u strongswan`.", file=sys.stderr)
            return 1
        return load_config(self, server_ip, psk)

    def interface(self) -> str:
        return json.loads(LOCAL_STATE.read_text())["interface"] if LOCAL_STATE.exists() else "any"

    def start_capture(self, name: str):
        self.sessions.mkdir(parents=True, exist_ok=True)
        self.sessions.chmod(0o755)
        # -Z root: write the file as root instead of dropping to the tcpdump user (which cannot write here).
        return subprocess.Popen(["tcpdump", "-i", self.interface(), "-U", "-n", "-Z", "root",
                                 "-w", str(self.sessions / f"{name}.pcap"), CAPTURE_FILTER],
                                stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

    def stop_capture(self, handle) -> None:
        handle.send_signal(signal.SIGINT)
        try:
            handle.wait(timeout=10)
        except subprocess.TimeoutExpired:
            handle.kill()

    def stop(self) -> None:
        for unit in ("strongswan", "strongswan-swanctl"):
            self.run("systemctl", "stop", unit, check=False)


def wait_for_charon(server, timeout: float = 30) -> bool:
    deadline = time.time() + timeout
    while time.time() < deadline:
        if server.run("swanctl", "--stats", check=False).returncode == 0:
            return True
        time.sleep(1)
    return False


def load_config(server, server_ip: str, psk: str) -> int:
    loaded = server.run("swanctl", "--load-all", check=False)
    if loaded.returncode != 0:
        print(f"strongSwan rejected the configuration:\n{loaded.stdout}{loaded.stderr}", file=sys.stderr)
        return 1
    print(phone_instructions(server_ip, psk))
    return 0


# --- commands ----------------------------------------------------------------------------------

def status(server, _: argparse.Namespace) -> int:
    sas = parse_sas(server.run("swanctl", "--list-sas").stdout)
    if not sas["established"]:
        print("No phone connected yet. Check the phone's VPN settings, that it is on the same network, "
              "and that the server address is this machine's bridged/LAN address.")
        return 1
    print(f"Phone connected: id '{sas.get('phone_id', '?')}', VPN address {sas.get('phone_virtual_ip', '?')}")
    print(f"  IKE SA : {sas.get('ike_proposal', '?')}")
    print(f"  ESP SA : {sas.get('esp', 'not installed yet')}  mode {sas.get('mode', '?')}, NAT-T {sas.get('nat_traversal', '?')}")
    if "packets_in" in sas:
        print(f"  data   : {sas['packets_in']} packets / {sas['bytes_in']:,} bytes received from the phone")
        if sas["packets_in"] == 0:
            print("  Warning: the tunnel is up but no data has arrived. Open a website on the phone; if this stays at 0, "
                  "the phone's encrypted packets are not reaching the server (see Troubleshooting in docs/whatsapp-live.md).")
    return 0


def record(server, args: argparse.Namespace) -> int:
    traffic = args.traffic or ACTIVITIES[args.activity]
    sas = parse_sas(server.run("swanctl", "--list-sas").stdout)
    if not sas["installed"]:
        print("No phone tunnel is up. Connect the phone's VPN first (check with `status`).", file=sys.stderr)
        return 1
    if sas.get("packets_in") == 0 and not args.force:
        print("The tunnel carries no data yet (0 packets from the phone), so the recording would be empty.\n"
              "Open a website on the phone and run `status` again. Use --force to record anyway.", file=sys.stderr)
        return 1
    server.sessions.mkdir(parents=True, exist_ok=True)
    name = next_name(args.app, args.activity, server.sessions)
    handle = server.start_capture(name)
    time.sleep(1.5)
    print(f"Recording {name} ({traffic}) for {args.seconds} s. Start the {args.activity} on the phone now. Ctrl+C stops early.")
    started = time.time()
    try:
        while (left := args.seconds - (time.time() - started)) > 0:
            print(f"  {int(left):4d} s left", end="\r", flush=True)
            time.sleep(min(1.0, left))
    except KeyboardInterrupt:
        print("\n  stopped early")
    seconds = time.time() - started
    server.stop_capture(handle)

    raw = server.run("swanctl", "--list-sas").stdout
    label = build_label(name, args.app, args.activity, traffic, seconds, parse_sas(raw), raw)
    (server.sessions / f"{name}.json").write_text(json.dumps(label, indent=2), encoding="utf-8")
    pcap = server.sessions / f"{name}.pcap"
    size = pcap.stat().st_size if pcap.exists() else 0
    rate = size / max(seconds, 1) / 1000
    profile = rate_profile(pcap) if size else {"median_kbps": 0.0, "bursts": []}
    label["rate_profile"] = profile
    (server.sessions / f"{name}.json").write_text(json.dumps(label, indent=2), encoding="utf-8")
    print(f"\nSaved {pcap} ({size:,} bytes; average {rate:.1f} KB/s, typical {profile['median_kbps']} KB/s) "
          f"and {name}.json  [ESP {label['negotiated']['esp']}]")
    # Sending files or loading status videos is bursty by nature: there the bursts are the activity itself.
    bursty = args.activity in BURSTY_ACTIVITIES
    if profile["bursts"]:
        print(("  Transfer bursts at: " if bursty else "  Bursts from other apps at: ")
              + ", ".join(f"{t}-{t + 10} s ({r} KB/s)" for t, r in profile["bursts"]))
    limit = MAX_RATE_KBPS.get(args.activity, float("inf"))
    if size < 20_000:
        print("  Warning: very little traffic was recorded. Was the phone's VPN connected and the app in use?")
    elif bursty:
        print("  Looks fine: bursts are expected while sending files or loading status videos.")
    elif profile["median_kbps"] > limit:
        print(f"  Warning: typically {profile['median_kbps']} KB/s, far more than a {args.activity} uses (normally "
              f"under {limit} KB/s). Other apps shared the tunnel the whole time (or the camera was on); record "
              f"again. Delete this one with:  sudo rm {server.sessions}/{name}.*")
    elif len(profile["bursts"]) > 2:
        print("  Note: several bursts from other apps; consider Data Saver and recording again.")
    else:
        print("  Looks clean.")
    return 0


def stop(server, _: argparse.Namespace) -> int:
    server.stop()
    print("VPN server stopped.")
    if platform.system() == "Windows":
        print("Re-enable Windows' IKE service (administrator):  sc config IKEEXT start= auto  and  net start IKEEXT")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--local", action="store_true", help="run strongSwan directly on this Linux machine (sudo)")
    parser.add_argument("--out", type=Path, help="where recordings are saved")
    commands = parser.add_subparsers(dest="command", required=True)
    serve_parser = commands.add_parser("serve", help="start the phone VPN server")
    serve_parser.add_argument("--lan-ip", help="the address the phone connects to (default: auto)")
    serve_parser.add_argument("--interface", help="local mode: interface to record on (default: the one holding --lan-ip)")
    serve_parser.add_argument("--psk", help="reuse a pre-shared key already entered on the phone")
    serve_parser.add_argument("--install", action="store_true", help="local mode: apt-get install strongSwan first")
    serve_parser.add_argument("--build", action="store_true", help="Docker mode: (re)build the strongSwan image first")
    serve_parser.add_argument("--force", action="store_true", help="Docker mode: run on Windows anyway")
    commands.add_parser("status", help="show the connected phone and negotiated settings")
    record_parser = commands.add_parser("record", help="record one labelled session")
    record_parser.add_argument("--app", default="whatsapp", type=lambda s: re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-"))
    record_parser.add_argument("--activity", required=True, choices=sorted(ACTIVITIES))
    record_parser.add_argument("--seconds", type=int, default=120)
    record_parser.add_argument("--traffic", choices=sorted(set(ACTIVITIES.values())), help="override the traffic class")
    record_parser.add_argument("--force", action="store_true", help="record even if the tunnel carries no data")
    commands.add_parser("stop", help="stop the phone VPN server")
    args = parser.parse_args()

    server = LocalServer(args.out) if args.local else DockerServer(args.out)
    try:
        if args.command == "serve":
            return server.serve(args)
        return {"status": status, "record": record, "stop": stop}[args.command](server, args)
    except RuntimeError as exc:
        print(exc, file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
