#!/usr/bin/env python3
"""Generate labelled IPsec captures with strongSwan in Docker.

For every scenario in testbed/configs/scenarios.json this writes
data/raw/testbed/capture_NNN.pcap (the on-the-wire IKE/ESP/AH traffic seen by
the initiator) and capture_NNN.json (authoritative ground truth), plus a
manifest.csv covering all captures.

    python testbed/scripts/run_testbed.py                  # all scenarios
    python testbed/scripts/run_testbed.py --only capture_005 capture_008
    python testbed/scripts/run_testbed.py --keep-running   # leave containers up

Requires Docker with Linux containers. Uses only the Python standard library.
"""
from __future__ import annotations

import argparse
import csv
import json
import secrets
import subprocess
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

TESTBED = Path(__file__).resolve().parents[1]
ROOT = TESTBED.parent
COMPOSE_FILE = TESTBED / "docker-compose.yml"
SCENARIOS = TESTBED / "configs" / "scenarios.json"
GENERATED = TESTBED / "generated"
OUTPUT = ROOT / "data" / "raw" / "testbed"

ADDRESSES = {
    "IPv4": {"moon": "172.30.0.10", "sun": "172.30.0.20"},
    "IPv6": {"moon": "fd00:30::10", "sun": "fd00:30::20"},
}
INNER = {
    "IPv4": {"moon": ("10.1.0.1", "10.1.0.0/24"), "sun": ("10.2.0.1", "10.2.0.0/24")},
    "IPv6": {"moon": ("fd00:1::1", "fd00:1::/64"), "sun": ("fd00:2::1", "fd00:2::/64")},
}
# Only on-the-wire IPsec traffic: IKE, NAT-T, ESP and AH. This also drops the
# decrypted copies of inbound packets that Linux re-injects on the interface.
CAPTURE_FILTER = "udp port 500 or udp port 4500 or ip proto 50 or ip proto 51 or ip6 proto 50 or ip6 proto 51"
TRAFFIC_SECONDS = 12


def compose(*args: str, check: bool = True, capture: bool = False) -> subprocess.CompletedProcess:
    command = ["docker", "compose", "-f", str(COMPOSE_FILE), *args]
    result = subprocess.run(command, text=True, capture_output=capture, check=False)
    if check and result.returncode != 0:
        detail = (result.stderr or result.stdout or "").strip() if capture else ""
        raise RuntimeError(f"Command failed ({result.returncode}): {' '.join(command)}\n{detail}")
    return result


def run_in(service: str, *command: str, check: bool = True, capture: bool = False) -> subprocess.CompletedProcess:
    return compose("exec", "-T", service, *command, check=check, capture=capture)


def render(scenario: dict, peer: str, other: str, psk: str) -> str:
    family = scenario["ip_version"]
    local, remote = ADDRESSES[family][peer], ADDRESSES[family][other]
    selectors = ""
    if scenario["mode"] == "tunnel":
        selectors = f"                local_ts = {INNER[family][peer][1]}\n                remote_ts = {INNER[family][other][1]}\n"
    # AH scenarios negotiate ah_proposals instead of esp_proposals.
    child_proposals = f"ah_proposals = {scenario['ah_proposal']}" if scenario.get("ah_proposal") else f"esp_proposals = {scenario['esp_proposal']}"
    # Short rekey timers make CREATE_CHILD_SA exchanges happen inside the capture (rand_time 0 keeps them regular).
    ike_timers = child_timers = ""
    if scenario.get("ike_rekey_seconds"):
        ike_timers = f"        rekey_time = {scenario['ike_rekey_seconds']}s\n        over_time = 10s\n        rand_time = 0s\n"
    if scenario.get("child_rekey_seconds"):
        child_timers = (f"                rekey_time = {scenario['child_rekey_seconds']}s\n"
                        f"                life_time = {scenario['child_rekey_seconds'] + 10}s\n                rand_time = 0s\n")
    return f"""# Generated by run_testbed.py for {scenario['id']} ({scenario['name']}). Do not edit.
connections {{
    testbed {{
        version = {scenario['ike_version']}
        local_addrs = {local}
        remote_addrs = {remote}
        proposals = {scenario['ike_proposal']}
        encap = {'yes' if scenario['encap'] else 'no'}
{ike_timers}        local {{
            auth = psk
        }}
        remote {{
            auth = psk
        }}
        children {{
            net {{
{selectors}                mode = {scenario['mode']}
                {child_proposals}
{child_timers}            }}
        }}
    }}
}}
secrets {{
    ike-testbed {{
        id-local = {local}
        id-remote = {remote}
        secret = "{psk}"
    }}
}}
"""


def wait_for_charon(service: str, timeout: float = 45) -> None:
    deadline = time.time() + timeout
    while time.time() < deadline:
        if run_in(service, "swanctl", "--stats", check=False, capture=True).returncode == 0:
            return
        time.sleep(1)
    raise RuntimeError(f"charon on {service} did not become ready")


def stop_capture() -> None:
    run_in("moon", "pkill", "-INT", "tcpdump", check=False)
    for _ in range(20):
        if run_in("moon", "pgrep", "tcpdump", check=False, capture=True).returncode != 0:
            return
        time.sleep(0.5)


def ground_truth(scenario: dict, pcap: str, version: str, sas: str, traffic: dict) -> dict:
    truth = scenario["truth"]
    no_ipsec = scenario.get("no_ipsec", False)
    child, ike = truth.get("child_sa", {}), truth.get("ike_sa", {})
    return {
        "capture_id": scenario["id"],
        "pcap_filename": pcap,
        "scenario": scenario["name"],
        "dataset_origin": "strongswan_testbed_capture",
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "strongswan_version": version,
        "ipsec_expected": not no_ipsec,
        "ipsec_protocol": None if no_ipsec else ("AH" if scenario.get("ah_proposal") else "ESP"),
        "mixed_normal_traffic": bool(scenario.get("plain_traffic")) or no_ipsec,
        # Flat fields follow the project ground-truth format; the nested SA blocks are authoritative.
        "ike_version": None if no_ipsec else f"IKEv{scenario['ike_version']}",
        "mode": None if no_ipsec else scenario["mode"].capitalize(),
        "ip_version": scenario["ip_version"],
        "nat_traversal": None if no_ipsec else scenario["encap"],
        "authentication": None if no_ipsec else "Pre-Shared Key",
        "encryption": child.get("encryption"),
        "dh_group": ike.get("dh_group"),
        "pfs": child.get("pfs"),
        "child_rekey_seconds": scenario.get("child_rekey_seconds"),
        "ike_rekey_seconds": scenario.get("ike_rekey_seconds"),
        "traffic": scenario["traffic"],
        "mode_observable": scenario.get("mode_observable", False),
        "ike_sa": ike,
        "child_sa": child,
        "strongswan_proposals": None if no_ipsec else {"ike": scenario["ike_proposal"], "child": scenario.get("ah_proposal") or scenario.get("esp_proposal")},
        "traffic_generator": traffic,
        "negotiated_sas": sas,
    }


def run_scenario(scenario: dict, index: int) -> dict:
    sid = scenario["id"]
    print(f"\n=== {sid}: {scenario['name']}", flush=True)
    psk = secrets.token_urlsafe(24)  # fresh per run; never stored outside the gitignored generated/ dir
    for peer, other in (("moon", "sun"), ("sun", "moon")):
        (GENERATED / peer / "testbed.conf").write_text(render(scenario, peer, other, psk), encoding="utf-8", newline="\n")

    compose("restart", "moon", "sun")
    no_ipsec = scenario.get("no_ipsec", False)
    for service in ("sun", "moon"):
        wait_for_charon(service)
        if not no_ipsec:
            run_in(service, "swanctl", "--load-all", capture=True)

    pcap = f"{sid}.pcap"
    (OUTPUT / pcap).unlink(missing_ok=True)
    # capture_all also records unprotected "normal" traffic next to (or instead of) IPsec.
    capture_filter = [] if scenario.get("capture_all") else [CAPTURE_FILTER]
    compose("exec", "-d", "moon", "tcpdump", "-i", "eth0", "-U", "-n", "-w", f"/captures/{pcap}", *capture_filter)
    time.sleep(2)
    seconds = scenario.get("seconds", TRAFFIC_SECONDS)
    family = scenario["ip_version"]
    outer_src, outer_dst = ADDRESSES[family]["moon"], ADDRESSES[family]["sun"]
    sas = ""
    try:
        if not no_ipsec:
            run_in("moon", "swanctl", "--initiate", "--ike", "testbed", "--child", "net", "--timeout", "30", capture=True)
            sas = run_in("moon", "swanctl", "--list-sas", capture=True).stdout
            if "INSTALLED" not in sas:
                raise RuntimeError(f"Child SA was not installed:\n{sas}")

        if scenario["mode"] == "tunnel" and not no_ipsec:
            src, dst = INNER[family]["moon"][0], INNER[family]["sun"][0]
        else:
            src, dst = outer_src, outer_dst
        traffic = {"kind": scenario["traffic"], "src": src, "dst": dst, "seconds": seconds, "seed": index}
        wait_for_servers()
        run_in("moon", "python3", "/usr/local/bin/traffic.py", "client", scenario["traffic"],
               "--src", src, "--dst", dst, "--seconds", str(seconds), "--seed", str(index))
        if plain := scenario.get("plain_traffic"):
            # Outer-to-outer traffic is outside the tunnel's selectors, so it crosses the wire unprotected.
            run_in("moon", "python3", "/usr/local/bin/traffic.py", "client", plain["kind"],
                   "--src", outer_src, "--dst", outer_dst, "--seconds", str(plain["seconds"]), "--seed", str(index + 100))
            traffic["plain"] = {"kind": plain["kind"], "src": outer_src, "dst": outer_dst, "seconds": plain["seconds"]}
        time.sleep(1)
        if not no_ipsec:
            run_in("moon", "swanctl", "--terminate", "--ike", "testbed", "--timeout", "10", check=False, capture=True)
        time.sleep(2)
    finally:
        stop_capture()

    version = run_in("moon", "swanctl", "--version", capture=True).stdout.strip()
    truth = ground_truth(scenario, pcap, version, sas, traffic)
    (OUTPUT / f"{sid}.json").write_text(json.dumps(truth, indent=2) + "\n", encoding="utf-8")
    size = (OUTPUT / pcap).stat().st_size
    print(f"    wrote {pcap} ({size:,} bytes) and {sid}.json", flush=True)
    return truth


TRAFFIC_CLASSES = ("Web", "Video", "VoIP", "Email", "Chat", "ICMP", "File-Transfer")
DATASET_OUTPUT = ROOT / "data" / "raw" / "traffic_sessions"


def bring_up(scenario: dict) -> str:
    psk = secrets.token_urlsafe(24)
    for peer, other in (("moon", "sun"), ("sun", "moon")):
        (GENERATED / peer / "testbed.conf").write_text(render(scenario, peer, other, psk), encoding="utf-8", newline="\n")
    compose("restart", "moon", "sun")
    for service in ("sun", "moon"):
        wait_for_charon(service)
        run_in(service, "swanctl", "--load-all", capture=True)
    run_in("moon", "swanctl", "--initiate", "--ike", "testbed", "--child", "net", "--timeout", "30", capture=True)
    sas = run_in("moon", "swanctl", "--list-sas", capture=True).stdout
    if "INSTALLED" not in sas:
        raise RuntimeError(f"Child SA was not installed:\n{sas}")
    return sas


def wait_for_servers(timeout: float = 60) -> None:
    """The responder generates its web content before listening; wait until every traffic port accepts."""
    probe = ("import socket\nfor port in (8080, 2525, 5222):\n    socket.create_connection(('127.0.0.1', port), 2).close()")
    deadline = time.time() + timeout
    while time.time() < deadline:
        if run_in("sun", "python3", "-c", probe, check=False, capture=True).returncode == 0:
            return
        time.sleep(1)
    raise RuntimeError("traffic servers on sun did not start")


def record_sessions(scenario: dict, repeats: int, seed_base: int) -> int:
    """Capture one pcap per traffic session over an established SA (ESP only, no IKE)."""
    import random

    family = scenario["ip_version"]
    if scenario["mode"] == "tunnel":
        src, dst = INNER[family]["moon"][0], INNER[family]["sun"][0]
    else:
        src, dst = ADDRESSES[family]["moon"], ADDRESSES[family]["sun"]
    rng = random.Random(seed_base)
    wait_for_servers()
    written = 0
    for repeat in range(repeats):
        for kind in TRAFFIC_CLASSES:
            seed = seed_base * 1000 + repeat * 10 + TRAFFIC_CLASSES.index(kind)
            seconds = rng.randint(8, 20)
            session_id = f"{scenario['id']}_{kind.lower()}_{repeat:02d}"
            pcap = f"{session_id}.pcap"
            recorded = False
            for attempt in range(2):
                (DATASET_OUTPUT / pcap).unlink(missing_ok=True)
                compose("exec", "-d", "moon", "tcpdump", "-i", "eth0", "-U", "-n", "-w", f"/sessions/{pcap}", CAPTURE_FILTER)
                time.sleep(1.5)
                try:
                    run_in("moon", "python3", "/usr/local/bin/traffic.py", "client", kind, "--src", src, "--dst", dst,
                           "--seconds", str(seconds), "--seed", str(seed))
                    time.sleep(1)
                    recorded = True
                except RuntimeError as exc:
                    print(f"    {session_id} attempt {attempt + 1} failed: {str(exc).splitlines()[0]}", file=sys.stderr, flush=True)
                finally:
                    stop_capture()
                if recorded:
                    break
            if not recorded:
                (DATASET_OUTPUT / pcap).unlink(missing_ok=True)
                continue
            label = {
                "session_id": session_id, "pcap_filename": pcap, "traffic": kind, "group": scenario["id"],
                "scenario": scenario["name"], "ike_version": f"IKEv{scenario['ike_version']}", "mode": scenario["mode"].capitalize(),
                "ip_version": family, "nat_traversal": scenario["encap"], "esp_proposal": scenario["esp_proposal"],
                "seconds": seconds, "seed": seed, "dataset_origin": "strongswan_testbed_capture",
            }
            (DATASET_OUTPUT / f"{session_id}.json").write_text(json.dumps(label, indent=2) + "\n", encoding="utf-8")
            written += 1
            print(f"    {session_id}: {(DATASET_OUTPUT / pcap).stat().st_size:,} bytes", flush=True)
    return written


def write_manifest() -> None:
    rows = []
    for path in sorted(OUTPUT.glob("capture_*.json")):
        truth = json.loads(path.read_text(encoding="utf-8"))
        rows.append({
            "capture_id": truth["capture_id"], "pcap_filename": truth["pcap_filename"], "scenario": truth["scenario"],
            "ike_version": truth["ike_version"], "mode": truth["mode"], "ip_version": truth["ip_version"],
            "nat_traversal": truth["nat_traversal"], "traffic": truth["traffic"],
            "ipsec_protocol": truth.get("ipsec_protocol", "ESP"), "mixed_normal_traffic": truth.get("mixed_normal_traffic", False),
            "ike_encryption": truth["ike_sa"].get("encryption"), "ike_integrity": truth["ike_sa"].get("integrity"),
            "ike_dh_group": truth["ike_sa"].get("dh_group"), "child_encryption": truth["child_sa"].get("encryption"),
            "child_integrity": truth["child_sa"].get("integrity"), "pfs": truth["child_sa"].get("pfs"),
            "child_rekey_seconds": truth.get("child_rekey_seconds"),
            "dataset_origin": truth["dataset_origin"],
        })
    if rows:
        with (OUTPUT / "manifest.csv").open("w", newline="", encoding="utf-8") as handle:
            writer = csv.DictWriter(handle, fieldnames=list(rows[0]))
            writer.writeheader()
            writer.writerows(rows)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--only", nargs="+", metavar="ID", help="scenario ids to run, e.g. capture_001")
    parser.add_argument("--keep-running", action="store_true", help="leave the containers running afterwards")
    parser.add_argument("--no-build", action="store_true", help="skip rebuilding the strongSwan image")
    parser.add_argument("--dataset", action="store_true",
                        help="record labelled traffic sessions for ML training into data/raw/traffic_sessions instead of scenario captures")
    parser.add_argument("--repeats", type=int, default=3, help="sessions per traffic class per scenario in --dataset mode")
    args = parser.parse_args()

    scenarios = json.loads(SCENARIOS.read_text(encoding="utf-8"))["scenarios"]
    selected = [(i, s) for i, s in enumerate(scenarios, start=1) if not args.only or s["id"] in args.only]
    if not selected:
        print("No matching scenarios.", file=sys.stderr)
        return 1

    for directory in (GENERATED / "moon", GENERATED / "sun", OUTPUT, DATASET_OUTPUT):
        directory.mkdir(parents=True, exist_ok=True)
    if not args.no_build:
        compose("build", "moon")
    compose("up", "-d")

    if args.dataset:
        total = 0
        try:
            for index, scenario in selected:
                print(f"\n=== {scenario['id']}: {scenario['name']} (dataset sessions)", flush=True)
                try:
                    bring_up(scenario)
                    total += record_sessions(scenario, args.repeats, index)
                except Exception as exc:
                    print(f"    FAILED: {exc}", file=sys.stderr, flush=True)
        finally:
            if not args.keep_running:
                compose("down", check=False)
        print(f"\n{total} labelled sessions in {DATASET_OUTPUT}")
        return 0

    failures = []
    try:
        for index, scenario in selected:
            try:
                run_scenario(scenario, index)
            except Exception as exc:  # keep going so one broken scenario does not block the rest
                failures.append(scenario["id"])
                print(f"    FAILED: {exc}", file=sys.stderr, flush=True)
    finally:
        write_manifest()
        if not args.keep_running:
            compose("down", check=False)

    print(f"\n{len(selected) - len(failures)}/{len(selected)} scenarios captured into {OUTPUT}")
    if failures:
        print(f"Failed: {', '.join(failures)}", file=sys.stderr)
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
