"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-25 23:12:43.029539
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('role', sa.Enum('admin', 'analyst', 'viewer', name='role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=True),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('captures',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_path', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('file_format', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('captures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_captures_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_captures_sha256'), ['sha256'], unique=False)

    op.create_table('analyses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('capture_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'completed', 'failed', name='analysisstatus'), nullable=False),
    sa.Column('packet_count', sa.Integer(), nullable=False),
    sa.Column('detected_protocols', sa.JSON(), nullable=False),
    sa.Column('ipsec_detected', sa.Boolean(), nullable=True),
    sa.Column('security_score', sa.Integer(), nullable=True),
    sa.Column('risk_level', sa.String(length=16), nullable=True),
    sa.Column('predicted_traffic', sa.String(length=32), nullable=True),
    sa.Column('tshark_version', sa.String(length=255), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['capture_id'], ['captures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analyses_capture_id'), ['capture_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analyses_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_analyses_risk_level'), ['risk_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_analyses_status'), ['status'], unique=False)

    op.create_table('ipsec_configurations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('analysis_id', sa.Uuid(), nullable=False),
    sa.Column('ipsec_protocol', sa.String(length=64), nullable=False),
    sa.Column('ike_version', sa.String(length=64), nullable=False),
    sa.Column('mode', sa.String(length=64), nullable=False),
    sa.Column('ip_version', sa.String(length=64), nullable=False),
    sa.Column('encryption_algorithm', sa.String(length=128), nullable=False),
    sa.Column('integrity_algorithm', sa.String(length=128), nullable=False),
    sa.Column('prf_algorithm', sa.String(length=128), nullable=False),
    sa.Column('authentication_method', sa.String(length=128), nullable=False),
    sa.Column('dh_group', sa.String(length=128), nullable=False),
    sa.Column('pfs', sa.String(length=64), nullable=False),
    sa.Column('sa_lifetime_seconds', sa.Integer(), nullable=True),
    sa.Column('nat_traversal', sa.String(length=64), nullable=False),
    sa.Column('replay_protection', sa.String(length=64), nullable=False),
    sa.Column('observations', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_id')
    )
    op.create_table('reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('analysis_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('executive', 'technical', name='reportkind'), nullable=False),
    sa.Column('stored_path', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('narrative_source', sa.String(length=128), nullable=False),
    sa.Column('generated_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['generated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_analysis_id'), ['analysis_id'], unique=False)

    op.create_table('security_findings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('analysis_id', sa.Uuid(), nullable=False),
    sa.Column('rule_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('condition', sa.Text(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('impact', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('security_findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_security_findings_analysis_id'), ['analysis_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_findings_rule_id'), ['rule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_findings_severity'), ['severity'], unique=False)

    op.create_table('traffic_predictions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('analysis_id', sa.Uuid(), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('predicted_label', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('probabilities', sa.JSON(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('traffic_predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_traffic_predictions_analysis_id'), ['analysis_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('traffic_predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_traffic_predictions_analysis_id'))

    op.drop_table('traffic_predictions')
    with op.batch_alter_table('security_findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_security_findings_severity'))
        batch_op.drop_index(batch_op.f('ix_security_findings_rule_id'))
        batch_op.drop_index(batch_op.f('ix_security_findings_analysis_id'))

    op.drop_table('security_findings')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_analysis_id'))

    op.drop_table('reports')
    op.drop_table('ipsec_configurations')
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analyses_status'))
        batch_op.drop_index(batch_op.f('ix_analyses_risk_level'))
        batch_op.drop_index(batch_op.f('ix_analyses_created_at'))
        batch_op.drop_index(batch_op.f('ix_analyses_capture_id'))

    op.drop_table('analyses')
    with op.batch_alter_table('captures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_captures_sha256'))
        batch_op.drop_index(batch_op.f('ix_captures_owner_id'))

    op.drop_table('captures')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
    if op.get_bind().dialect.name == 'postgresql':
        for enum in ('reportkind', 'analysisstatus', 'role'):
            op.execute(f'DROP TYPE IF EXISTS {enum}')
